version: "3"
networks:
    waiting_for_conteiner:
services:
    db:
        image: yandex/clickhouse-server
        hostname: clickhouse
        container_name: clickhouse-server
        ports:
            - "8123:8123"
            - "9000:9000"
            - "9009:9009"
        volumes:
            - ./db/config.xml:/etc/clickhouse-server/config.xml
            - ./db/users.xml:/etc/clickhouse-server/users.xml
            - ./db/data:/var/lib/clickhouse
        networks:
            - waiting_for_conteiner
        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
    app:
        build: 
            context: .
            dockerfile: app.dockerfile
        container_name: algo_app
        volumes:
            - ./app:/usr/src/app
        depends_on:
            - "db"
        networks:
            - waiting_for_conteiner

